# Generated by Django 2.1.15 on 2019-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolList',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=150)),
                ('Price', models.CharField(max_length=50)),
                ('Changes', models.CharField(max_length=50)),
                ('UpdatedOn', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'PetrolList',
                'verbose_name_plural': 'PetrolLists',
            },
        ),
    ]
