# Generated by Django 2.1.15 on 2019-12-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petrollist',
            options={},
        ),
    ]
