# Generated by Django 2.1.15 on 2019-12-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0002_auto_20191218_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrollist',
            name='FuelType',
            field=models.IntegerField(default=0),
        ),
    ]
